# Generated by Django 3.1.6 on 2021-02-21 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('twon', models.CharField(choices=[('X', 'Default'), ('1', 'DAKAR'), ('9', 'Dakar Plateau'), ('2', 'Dakar Plateau GUEULE TAPEE'), ('3', 'Dakar Plateau FASS'), ('4', 'Dakar Plateau COLOBANE'), ('5', 'Dakar Plateau POINT E'), ('6', 'Dakar Plateau AMITIE'), ('7', 'Dakar Plateau GOREE'), ('8', 'Dakar Plateau MEDINA'), ('10', 'Parcelles Assainies'), ('11', 'Parcelles Assainies Grand YOFF'), ('12', 'Parcelles Assainies PATTE D OIE'), ('13', 'Parcelles Assainies CAMBERENE'), ('14', 'Grand Dakar'), ('15', 'Grand Dakar BISCUITERIE'), ('16', 'Grand Dakar HLM'), ('17', 'Grand Dakar HANN BEL AIR'), ('18', 'Grand Dakar DIEUPPEUL DERKLE'), ('19', 'Grand Dakar SICAP LIBERTE'), ('20', 'Almadies'), ('21', 'Almadies YOFF'), ('22', 'Almadies MERMOZ SACRE COEUR'), ('23', 'Almadies NGOR'), ('24', 'Almadies OUAKAM'), ('25', 'Guédiawaye'), ('26', 'Guédiawaye GOLF SUD'), ('27', 'Guédiawaye MEDINA GOUNASS'), ('28', 'Guédiawaye NDIAREME'), ('29', 'Guédiawaye SAM NOTAIRE'), ('30', 'Guédiawaye WAKHINANE NIMZAT'), ('31', 'Pikine'), ('32', 'Pikine Dagoudane DALIFORT'), ('33', 'Pikine Dagoudane DJIDA THIAROYE KAO'), ('34', 'Pikine Dagoudane GUINAW RAIL NORD'), ('35', 'Pikine Dagoudane GUINAW RAIL SUD'), ('36', 'Pikine Dagoudane EST'), ('37', 'Pikine Dagoudane NORD'), ('38', 'Pikine Dagoudane OUEST'), ('39', 'Niayes KEUR MASSAR'), ('40', 'Niayes MALIKA'), ('41', 'Niayes YEUMBEUL NORD'), ('42', 'Niayes YEUMBEUL SUD'), ('43', 'Thiaroye MBAO'), ('44', 'Thiaroye SICAP MBAO'), ('45', 'THIAROYE GARE'), ('46', 'THIAROYE SUR MER'), ('47', 'THIAROYE TIVAVOUANE DIAKSAO'), ('48', 'Thiaroye DIAMAGUENE'), ('49', 'RUFISQUE EST'), ('50', 'RUFISQUE NORD'), ('51', 'RUFISQUE OUEST'), ('52', 'LIBERTE 1'), ('53', 'LIBERTE 2'), ('54', 'LIBERTE 3'), ('55', 'LIBERTE 4'), ('56', 'LIBERTE 5'), ('57', 'LIBERTE 6'), ('58', 'SACREE COEUR'), ('59', 'MAMELLE'), ('60', 'NORD FOIR'), ('61', 'OUEST FOIR'), ('62', 'FOIR')], default='1', max_length=10)),
                ('tel', models.CharField(default='X', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('being_delivered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('payment_option', models.CharField(blank=True, max_length=2, null=True)),
                ('sessionID', models.CharField(default='X', max_length=200, null=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='product.address')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nom du produit')),
                ('code_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(verbose_name='Prix')),
                ('purchase_price', models.FloatField(blank=True, null=True, verbose_name="Prix d'achat")),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='Prix réduit')),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('X', 'default')], max_length=1, verbose_name='Label')),
                ('description', models.TextField(verbose_name='Description')),
                ('gender', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('E', 'Enfant')], default='X', max_length=1, verbose_name='Genre')),
                ('color', models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('R', 'Red'), ('X', 'Default')], default='X', max_length=2, verbose_name='Couleur')),
                ('size_cloth', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('X', 'Default')], default='X', max_length=2, verbose_name='Taille')),
                ('size_shoes', models.CharField(choices=[('32', 'Adulte'), ('20', 'Enfant'), ('45', 'Adulte2'), ('X', 'Default')], default='X', max_length=2, verbose_name='Pointure')),
                ('star', models.IntegerField(default=0)),
                ('provider', models.CharField(default='proximarket', max_length=100, verbose_name='Fournisseur')),
                ('stock', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('X', 'Delete')], default='D', max_length=1, verbose_name='Statut')),
                ('origin', models.CharField(choices=[('L', 'Locale'), ('I', 'Internationale'), ('X', 'Default')], default='X', max_length=2)),
                ('marque', models.CharField(blank=True, default='Générique', max_length=100, null=True)),
                ('categorie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorie.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('produit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('sessionID', models.CharField(default='X', max_length=200)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produit')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='produits',
            field=models.ManyToManyField(to='product.OrderProduit'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='product.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
