# Generated by Django 3.1.6 on 2021-02-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_address_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='twon',
            new_name='town',
        ),
    ]
