# Generated by Django 3.1.6 on 2021-02-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210222_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='tel',
            new_name='telephone',
        ),
    ]
