# Generated by Django 3.1.6 on 2021-02-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
        ('product', '0007_auto_20210222_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='categorie.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Nom du produit'),
        ),
    ]
