# Generated by Django 3.1.7 on 2021-02-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210222_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='gender',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('E', 'Enfant'), ('X', 'Default')], default='X', max_length=1, verbose_name='Genre'),
        ),
    ]
