# Generated by Django 3.1.6 on 2021-02-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(blank='true', max_length=200, null=True)),
                ('Prenom', models.CharField(blank='true', max_length=200, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('Sujet', models.CharField(default='Contact', max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Date_modification', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_treat', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
            ],
        ),
    ]
